environments:
  - name: env-tg
    path: "environment.yaml"
    variables:
      max_containers: 2
name: module-helm-chart
modules:
  - name: helmchart
    type: helm-chart
    chart: redis
    chart_version: "16.12.0"
    repository: "https://charts.bitnami.com/bitnami"
