# This values.yaml file contains the values needed to enable HA mode.
# Usage:
#   helm install -f values.yaml -f values-ha.yaml

enablePodAntiAffinity: true

# We explicitly set the annotations in ingress-nginx and k8s service, but leaving this here for whatever else a user
# may add.
proxy:
  resources:
    cpu:
      request: 50m
      limit: ""
    memory:
      limit: 100Mi
      request: 20Mi

# controller configuration
controllerReplicas: 3
controllerResources: &controller_resources
  cpu: &controller_resources_cpu
    limit: ""
    request: 50m
  memory:
    limit: ""
    request: 50Mi
destinationResources: *controller_resources
publicAPIResources: *controller_resources

# identity configuration
identityResources:
  cpu: *controller_resources_cpu
  memory:
    limit: ""
    request: 10Mi

# proxy injector configuration
proxyInjectorResources: *controller_resources
webhookFailurePolicy: Fail

# service profile validator configuration
spValidatorResources: *controller_resources

# proxy injector configuration
proxyInjector:
  # -- Namespace selector used by admission webhook. If not set defaults to all
  # namespaces without the annotation
  # config.linkerd.io/admission-webhooks=disabled
  namespaceSelector:
    matchExpressions:
      - key: config.linkerd.io/admission-webhooks
        operator: NotIn
        values:
          - disabled
      - key: kubernetes.io/metadata.name
        operator: NotIn
        values:
          - kube-system
    