apiVersion: v1
kind: Service
metadata:
  name: {{ include "k8s-service.serviceName" . }}
  labels:
    {{- include "k8s-service.labels" . | nindent 4 }}
  namespace: {{ include "k8s-service.namespaceName" . }}
spec:
  ports:
    - port: 80
      targetPort: main
      protocol: TCP
      name: main
  {{- if ne (len .Values.persistentStorage) 0 }}
  clusterIP: None
  {{- end }}
  selector:
    {{- include "k8s-service.selectorLabels" . | nindent 4 }}
