apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-service.serviceAccountName" . }}
  labels:
    {{- include "k8s-service.labels" . | nindent 4 }}
  annotations:
    iam.gke.io/gcp-service-account: {{ .Values.googleServiceAccount }}
  namespace: {{ include "k8s-service.namespaceName" . }}
