required_providers:
  google:
    source: "hashicorp/google"
    version: "3.90.1"
  helm:
    source: "hashicorp/helm"
    version: "2.4.1"
backend:
  gcs:
    bucket: "{state_storage}"
    prefix: "{layer_name}"
validator:
  name: str()
  org_name: regex('^[a-z0-9-]{,15}$', name="Valid identifier, regex='[a-z0-9-]{,15}'")
  providers:
    google:
      region: str()
      project: str()
  modules: list(module())
service_validator:
  - environments: list(include('env'), required=False)
    name: str()
    modules: list(module())
  - env:
      name: str()
      path: str()
      variables: map(required=False)
      vars: map(required=False)
module_aliases:
  postgres: gcp-postgres
  redis: gcp-redis
  k8s-service: gcp-k8s-service
  base: gcp-base
  k8s-base: gcp-k8s-base
  k8s-cluster: gcp-gke
  mysql: gcp-mysql
  dns: gcp-dns