required_providers:
  google:
    source: "hashicorp/google"
    version: "3.77.0"
backend:
  gcs:
    bucket: "{state_storage}"
    prefix: "{layer_name}"
validator:
  name: str()
  org_name: regex('^[a-z0-9-]{,15}$', name="Valid identifier, regex='[a-z0-9-]{,15}'")
  providers:
    google:
      region: str()
      project: str()
  modules: list(module())
module_aliases:
  postgres: gcp-postgres
  redis: gcp-redis
  k8s-service: gcp-k8s-service
  base: gcp-base
  k8s-base: gcp-k8s-base
  k8s-cluster: gcp-gke
  dns: gcp-dns