when: << pipeline.parameters.run-cnd-version-compare >>
jobs:
  - get-all-parameter-values
  - build-test-service-image
  - download-opta-version:
      name: "download-opta-version-v1"
      opta-version: << pipeline.parameters.opta-version-v1 >>
  - aws-create-env-stable-version:
      name: "aws-create-env-v1"
      requires:
        - build-test-service-image
        - download-opta-version-v1
  - aws-test-k8s-manifest-apply-stable-version:
      name: "aws-test-k8s-manifest-apply-v1"
      requires:
        -  aws-create-env-v1
  - aws-test-cloudfront-apply-stable-version:
      name: "aws-test-cloudfront-apply-v1"
      requires:
        - aws-create-env-v1
  - aws-test-lambda-function-apply-stable-version:
      name: "aws-test-lambda-function-apply-v1"
      requires:
        - aws-create-env-v1
  - aws-test-service-helm-apply-stable-version:
      name: "aws-test-service-helm-apply-v1"
      requires:
        - aws-create-env-v1
  - aws-test-service-redis-apply-stable-version:
      name: "aws-test-service-redis-apply-v1"
      requires:
        - aws-create-env-v1
  - aws-test-service-docdb-apply-stable-version:
      name: "aws-test-service-docdb-apply-v1"
      requires:
        - aws-create-env-v1
  - aws-test-service-s3-apply-stable-version:
      name: "aws-test-service-s3-apply-v1"
      requires:
        - aws-create-env-v1
  - aws-test-websocket-apply-stable-version:
      name: "aws-test-websocket-apply-v1"
      requires:
        - aws-create-env-v1
  - download-opta-version:
      name: "download-opta-version-v2"
      opta-version: << pipeline.parameters.opta-version-v2 >>
      requires:
        - aws-test-k8s-manifest-apply-v1
        - aws-test-cloudfront-apply-v1
        - aws-test-lambda-function-apply-v1
        - aws-test-service-helm-apply-v1
        - aws-test-service-redis-apply-v1
        - aws-test-service-docdb-apply-v1
        - aws-test-service-s3-apply-v1
        - aws-test-websocket-apply-v1
        - gcp-test-k8s-manifest-apply-v1
        - gcp-test-service-gcs-apply-v1
        - gcp-test-service-helm-apply-v1
        - gcp-test-service-redis-apply-v1
  - aws-create-env-stable-version:
      name: "aws-create-env-v2"
      requires:
        - aws-create-env-v1
        - download-opta-version-v2
  - aws-test-k8s-manifest-apply-stable-version:
      name: "aws-test-k8s-manifest-apply-v2"
      requires:
        - aws-create-env-v2
        - aws-test-k8s-manifest-apply-v1
  - aws-test-cloudfront-apply-stable-version:
      name: "aws-test-cloudfront-apply-v2"
      requires:
        - aws-create-env-v2
        - aws-test-cloudfront-apply-v1
  - aws-test-lambda-function-apply-stable-version:
      name: "aws-test-lambda-function-apply-v2"
      requires:
        - aws-create-env-v2
        - aws-test-lambda-function-apply-v1
  - aws-test-service-helm-apply-stable-version:
      name: "aws-test-service-helm-apply-v2"
      requires:
        - aws-create-env-v2
        - aws-test-service-helm-apply-v1
  - aws-test-service-redis-apply-stable-version:
      name: "aws-test-service-redis-apply-v2"
      requires:
        - aws-create-env-v2
        - aws-test-service-redis-apply-v1
  - aws-test-service-docdb-apply-stable-version:
      name: "aws-test-service-docdb-apply-v2"
      requires:
        - aws-create-env-v2
        - aws-test-service-docdb-apply-v1
  - aws-test-service-s3-apply-stable-version:
      name: "aws-test-service-s3-apply-v2"
      requires:
        - aws-create-env-v2
        - aws-test-service-s3-apply-v1
  - aws-test-websocket-apply-stable-version:
      name: "aws-test-websocket-apply-v2"
      requires:
        - aws-create-env-v2
        - aws-test-websocket-apply-v1
  - aws-test-k8s-manifest-destroy-stable-version:
      requires:
        - aws-test-k8s-manifest-apply-v2
  - aws-test-cloudfront-destroy-stable-version:
      requires:
        - aws-test-cloudfront-apply-v2
  - aws-test-lambda-function-destroy-stable-version:
      requires:
        - aws-test-lambda-function-apply-v2
  - aws-test-service-helm-destroy-stable-version:
      requires:
        - aws-test-service-helm-apply-v2
  - aws-test-service-redis-destroy-stable-version:
      requires:
        - aws-test-service-redis-apply-v2
  - aws-test-service-docdb-destroy-stable-version:
      requires:
        - aws-test-service-docdb-apply-v2
  - aws-test-service-s3-destroy-stable-version:
      requires:
        - aws-test-service-s3-apply-v2
  - aws-test-websocket-destroy-stable-version:
      requires:
        - aws-test-websocket-apply-v2
  - aws-destroy-env-stable-version:
      name: "aws-destroy-env"
      requires:
        - aws-test-k8s-manifest-destroy-stable-version
        - aws-test-cloudfront-destroy-stable-version
        - aws-test-lambda-function-destroy-stable-version
        - aws-test-service-helm-destroy-stable-version
        - aws-test-service-redis-destroy-stable-version
        - aws-test-service-docdb-destroy-stable-version
        - aws-test-service-s3-destroy-stable-version
        - aws-test-websocket-destroy-stable-version
  - gcp-create-env-stable-version:
      name: "gcp-create-env-v1"
      requires:
        - build-test-service-image
        - download-opta-version-v1
  - gcp-test-k8s-manifest-apply-stable-version:
      name: "gcp-test-k8s-manifest-apply-v1"
      requires:
        - gcp-create-env-v1
  - gcp-test-service-gcs-apply-stable-version:
      name: "gcp-test-service-gcs-apply-v1"
      requires:
        - gcp-create-env-v1
  - gcp-test-service-helm-apply-stable-version:
      name: "gcp-test-service-helm-apply-v1"
      requires:
        - gcp-create-env-v1
  - gcp-test-service-redis-apply-stable-version:
      name: "gcp-test-service-redis-apply-v1"
      requires:
        - gcp-create-env-v1
  - gcp-create-env-stable-version:
      name: "gcp-create-env-v2"
      requires:
        - gcp-create-env-v1
        - download-opta-version-v2
  - gcp-test-k8s-manifest-apply-stable-version:
      name: "gcp-test-k8s-manifest-apply-v2"
      requires:
        - gcp-create-env-v2
        - gcp-test-k8s-manifest-apply-v1
  - gcp-test-service-gcs-apply-stable-version:
      name: "gcp-test-service-gcs-apply-v2"
      requires:
        - gcp-create-env-v2
        - gcp-test-service-gcs-apply-v1
  - gcp-test-service-helm-apply-stable-version:
      name: "gcp-test-service-helm-apply-v2"
      requires:
        - gcp-create-env-v2
        - gcp-test-service-helm-apply-v1
  - gcp-test-service-redis-apply-stable-version:
      name: "gcp-test-service-redis-apply-v2"
      requires:
        - gcp-create-env-v2
        - gcp-test-service-redis-apply-v1
  - gcp-test-k8s-manifest-destroy-stable-version:
      requires:
        - gcp-test-k8s-manifest-apply-v2
  - gcp-test-service-gcs-destroy-stable-version:
      requires:
        - gcp-test-service-gcs-apply-v2
  - gcp-test-service-helm-destroy-stable-version:
      requires:
        - gcp-test-service-helm-apply-v2
  - gcp-test-service-redis-destroy-stable-version:
      requires:
        - gcp-test-service-redis-apply-v2
  - gcp-destroy-env-stable-version:
      name: "gcp-destroy-env"
      requires:
        - gcp-test-k8s-manifest-destroy-stable-version
        - gcp-test-service-gcs-destroy-stable-version
        - gcp-test-service-helm-destroy-stable-version
        - gcp-test-service-redis-destroy-stable-version
