parameters:
  run-create-and-destroy:
    type: boolean
    default: false
  run-create-and-destroy-azure:
    type: boolean
    default: false
  run-create-and-destroy-aws:
    type: boolean
    default: false
  run-create-and-destroy-gcp:
    type: boolean
    default: false
  run-destroy-gcp-env:
    type: boolean
    default: false
  run-destroy-aws-env:
    type: boolean
    default: false
  run-destroy-azure-env:
    type: boolean
    default: false
  run-destroy-all-envs:
    type: boolean
    default: false
  run-ci:
    type: boolean
    default: false
  run-create-destroy-local:
    type: boolean
    default: false
  run-service-mesh-e2e:
    type: boolean
    default: false
  test-aws-lambda:
    type: boolean
    default: false
  run-release-vs-stable:
    type: boolean
    default: false
  test-aws-dns:
    type: boolean
    default: false
  run-destroy-aws-dns-false:
    type: boolean
    default: false
  run-destroy-aws-dns-true:
    type: boolean
    default: false
  test:
    type: boolean
    default: false
  ci-use-diff-env:
    type: boolean
    default: false
  ci-env-name:
    type: string
    default: 'env-ci'
  ci-env-region-aws:
    type: string
    default: 'us-east-2'
  ci-env-region-gcp:
    type: string
    default: 'us-central1'
  run-opta-terraform-generate-test:
    type: boolean
    default: false
  opta-version-v1:
    type: string
    default: ''
  opta-version-v2:
    type: string
    default: ''
  run-cnd-version-compare:
    type: boolean
    default: false
  run-destroy-stable-version:
    type: boolean
    default: false