{{- range $index, $val := .Values.uriComponents }}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name:  {{ include "k8s-service.fullname" $ }}-{{ $index }}
  namespace: {{ include "k8s-service.namespaceName" $ }}
  labels:
    {{- include "k8s-service.labels" $ | nindent 4 }}
  annotations:
    {{- if $.Values.stickySession }}
    nginx.ingress.kubernetes.io/affinity: "cookie"
    nginx.ingress.kubernetes.io/session-cookie-name: "opta-cookie"
    nginx.ingress.kubernetes.io/session-cookie-expires: {{ $.Values.stickySessionMaxAge | quote }}
    nginx.ingress.kubernetes.io/session-cookie-max-age: {{ $.Values.stickySessionMaxAge | quote }}
    {{- end }}
    {{- if $.Values.consistentHash }}
    nginx.ingress.kubernetes.io/upstream-hash-by: {{ $.Values.consistentHash }}
    {{- end }}
    {{- if and ( ne $val.pathPrefix "/") (not $.Values.keepPathPrefix) }}
    nginx.ingress.kubernetes.io/rewrite-target: "/$2"
    {{- end }}
    {{- if and ( ne $val.pathPrefix "/") $.Values.keepPathPrefix }}
    nginx.ingress.kubernetes.io/rewrite-target: "{{ $val.pathPrefix }}$1$2"
    {{- end }}
    {{ if hasKey $.Values.port "grpc" }}
    nginx.ingress.kubernetes.io/backend-protocol: "GRPC"
    {{- end }}
    cert-manager.io/cluster-issuer: opta-selfsigned
    kubernetes.io/ingress.class: "nginx"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
      grpc_set_header l5d-dst-override $service_name.$namespace.svc.cluster.local:$service_port;
    {{/* For websockets */}}
    {{ if hasKey $.Values.port "tcp" }}
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
    {{- end }}
    {{ if hasKey $.Values.annotations "ingress" }}
    {{- range $k, $v := $.Values.annotations.ingress }}
    {{ $k }}: {{ $v }}
    {{- end }}
    {{- end }}
spec:
  rules:
    - {{ if not (eq $val.domain "all" ) }}
      host: {{ $val.domain }}
      {{ end }}
      http:
        paths:
          - path: {{ $val.pathPrefix }}{{ if not (eq $val.pathPrefix "/") }}(/|$)(.*){{ end }}
            backend:
              serviceName: {{ include "k8s-service.serviceName" $ }}
              servicePort: 80
---
{{- end }}
