type: regex('aws-dns')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
domain: str(required=False)
delegated: any(required=False)