type: regex('aws-sns')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
fifo: bool(required=False)
content_based_deduplication: bool(required=False)
sqs_subscribers: list(str(), required=False)
