type: regex('aws-sqs')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
fifo: bool(required=False)
content_based_deduplication: bool(required=False)
delay_seconds: int(required=False)
message_retention_seconds: int(required=False)
receive_wait_time_seconds: int(required=False)