type: regex('aws-s3')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
bucket_name: str(required=True)
s3_log_bucket_name: str(required=False)
same_region_replication: bool(required=False)
block_public: any(required=False)
bucket_policy: any(required=False)
cors_rule: include('cors', required=False)
---
cors:
  allowed_origins: list(str(), required=False)
  allowed_headers: list(str(), required=False)
  allowed_methods: list(str(), required=False)
  expose_headers: list(str(), required=False)
  max_age_seconds: int(required=False)
