type: regex('aws-k8s-base')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
openid_provider_url: str(required=False)
openid_provider_arn: str(required=False)
nginx_high_availability: bool(required=False)
linkerd_high_availability: bool(required=False)
linkerd_enabled: bool(required=False)
domain: any(required=False)
cert_arn: any(required=False)
admin_arns: list(str(), required=False)
nginx_config: any(required=False)
