type: regex('aws-nodegroup')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
max_nodes: any(str(), int(), required=False)
min_nodes: any(str(), int(), required=False)
node_disk_size: any(str(), int(), required=False)
node_instance_type: str(required=False)
use_gpu: bool(required=False)
labels: map(str(), str(), required=False)
spot_instances: bool(required=False)
