type: regex('azure-aks')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
max_nodes: any(str(), int(), required=False)
min_nodes: any(str(), int(), required=False)
node_disk_size: any(str(), int(), required=False)
node_instance_type: str(required=False)
admin_group_object_ids: list(str(), require=False)
kubernetes_version: str(required=False)