type: regex('azure-postgres')
name: str()
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
engine_version: str(required=False)
sku_name: str(required=False)
