type: regex('datadog')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
api_key: str(required=False)
values: any(required=False)