type: regex('gcp-gke')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
max_nodes: any(str(), int(), required=False)
min_nodes: any(str(), int(), required=False)
node_disk_size: any(str(), int(), required=False)
node_instance_type: str(required=False)
gke_channel: str(required=False)
