type: regex('gcp-gcs')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
bucket_name: str(required=False)
block_public: any(required=False)
