type: regex('helm-chart')
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
repository: str(required=False)
chart: str(required=True)
namespace: str(required=False)
create_namespace: bool(required=False)
atomic: bool(required=False)
cleanup_on_fail: bool(required=False)
version: str(required=False)
values_file: str(required=False)
values: any(required=False)
timeout: int(required=False)
dependency_update: bool(required=False)
