type: regex('k8s-service')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
image: str(required=False)
port: any(required=False)
tag: any(required=False)
env_vars: list(include('env-var'), required=False)
secrets: list(str(), required=False)
autoscaling_target_cpu_percentage: any(str(), int(), required=False)
autoscaling_target_mem_percentage: any(str(), int(), required=False)
liveness_probe_path: str(required=False)
readiness_probe_path: str(required=False)
healthcheck_path: str(required=False)
resource_request: any(required=False)
public_uri: any(str(), list(), required=False)
domain: any(required=False)
openid_provider_url: str(required=False)
openid_provider_arn: str(required=False)
iam_policy: any(required=False)
additional_iam_roles: any(required=False)
min_containers: any(str(), int(), required=False)
max_containers: any(str(), int(), required=False)
links: list(any(str(), map()), required=False)
grpc: bool(required=False)
---
env-var:
  name: str(required=False)
  value: str()
