type: regex('k8s-base')
name: str(required=False)
env_name: str(required=False)
layer_name: str(required=False)
module_name: str(required=False)
openid_provider_url: str(required=False)
openid_provider_arn: str(required=False)
high_availability: any(required=False)
domain: any(required=False)
cert_arn: any(required=False)