any(include('service-schema'), include('environment-schema'))
---
environment-schema:
  name: str()
  org_name: str()
  providers:
    aws:
      region: str()
      account_id: int()
  modules: list(module())
---
service-schema:
  environments: list(include('env'), required=False)
  name: str()
  modules: list(module())
env:
  name: str()
  path: str()
  vars: map()
