environments: []
name: ""
modules:
  - type: k8s-service
    name: app
    port:
      http: 80
    image: AUTO
    env_vars:
      APPENV: "{env}"
    public_uri: "{parent.domain}"
    resource_request:
      cpu: 100 # in millicores
      memory: 1024 # in megabytes
