# Note:
# Added terraform refresh and terraform state rm before planning destroy 
# because kms key is coming as a deposed object in terraform state,.
executor: ubuntu-machine
steps:
  - install-opta-dependencies
  - attach_workspace:
      at: ~/
  - run:
      name: "Destroy Terraform Generated Environment"
      command: |
        cd $HOME/generated-tf-files-aws
        terraform init
        terraform refresh
        terraform state rm module.base.aws_ebs_default_kms_key.default
        terraform plan -compact-warnings -lock=false -input=false -out=tf.plan -target=module.base -target=module.k8scluster -target=module.k8sbase -destroy
        terraform apply -compact-warnings -auto-approve tf.plan
  - store_artifacts:
      path: ~/generated-tf-files-aws
  - persist_to_workspace:
      root: ~/
      paths:
        - generated-tf-files-aws