executor: python-docker
environment:
  OPTA_DISABLE_REPORTING: "true"
steps:
  - checkout-opta
  - when:
      condition: << pipeline.parameters.ci-use-diff-env >>
      steps:
        - remake-environment-configs
  - attach_workspace:
      at: ./
  - install-opta-dependencies
  - aws-cli/install
  - aws-cli/setup
  - run:
      name: "Update KUBECONFIG"
      command: echo 'export KUBECONFIG="$HOME/kube_config.yaml"' >> $BASH_ENV
  - run:
      name: "Configure Kubectl"
      command: |
        ./dist/opta/opta configure-kubectl \
        --config ./.circleci/ci-tests/create-and-destroy-aws/environment.yml
  - run:
      name: "Apply K8s Manifest with Opta"
      command: |
        ./dist/opta/opta apply \
        --env awsenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-aws/k8s-manifest.yaml \
        --auto-approve
  - run:
      name: "Test manifest pod creation"
      command: |
        kubectl get pod -n default nginx
        exit $?
  - run:
      name: "Destroy K8s Manifest with Opta"
      command: |
        yes | ./dist/opta/opta destroy \
        --env awsenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-aws/k8s-manifest.yaml \
        --auto-approve || if [[ $? -eq 141 ]]; then true; else exit $?; fi