executor: python-docker
environment:
  OPTA_DISABLE_REPORTING: "true"
steps:
  - checkout-opta
  - when:
      condition: << pipeline.parameters.ci-use-diff-env >>
      steps:
        - remake-environment-configs
  - attach_workspace:
      at: ~/
  - attach_workspace:
      at: ./
  - install-opta-dependencies
  - aws-cli/install
  - aws-cli/setup
  - run:
      name: "Deploy test-service-helm"
      command: |
        $HOME/.opta/opta apply \
        --env awsenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-aws/service-helm.yml \
        --auto-approve
