executor: ubuntu-machine
steps:
  - install-opta-dependencies
  - attach_workspace:
      at: ~/
  - run:
      name: "Create Terraform Generated Hello Opta Service"
      command: |
        cd $HOME/generated-tf-files-aws
        terraform init
        terraform refresh
        terraform plan -compact-warnings -lock=false -input=false -out=tf.plan -target=module.hello
        terraform apply -compact-warnings -auto-approve tf.plan
  - run:
      name: "Sleep 120 seconds"
      command: |
        sleep 120
  - run:
      name: "Get Output and Test Load Balancer"
      command: |
        cd $HOME/generated-tf-files-aws
        terraform output -json >> terraform_output.json
        export LOAD_BALANCER=`cat terraform_output.json | jq -r '.load_balancer_raw_dns' |jq -r '.value'`
        echo $LOAD_BALANCER
        curl "$LOAD_BALANCER/hello"
        echo "1"
  - run:
      name: "Sleep 120 seconds"
      command: |
        sleep 120
  - run:
      name: "Destroy Terraform Generated Hello Opta Service"
      command: |
        cd $HOME/generated-tf-files-aws
        terraform plan -compact-warnings -lock=false -input=false -out=tf.plan -target=module.hello -destroy
        terraform apply -compact-warnings -auto-approve tf.plan
  - persist_to_workspace:
      root: ~/
      paths:
        - generated-tf-files-aws
  - store_artifacts:
      path: ~/generated-tf-files-aws