executor: python-docker
environment:
  OPTA_DISABLE_REPORTING: "true"
steps:
  - checkout
  - when:
      condition: << pipeline.parameters.ci-use-diff-env >>
      steps:
        - remake-environment-configs
  - attach_workspace:
      at: ./
  - attach_workspace:
      at: ~/
  - install-opta-dependencies
  - azure-cli/install
  - azure-cli/login-with-service-principal
  - run:
      name: Run opta apply on environment configuration
      command: |
        ./dist/opta/opta apply \
        --config ./.circleci/ci-tests/create-and-destroy-azure/environment.yaml \
        --auto-approve \
        --refresh