executor: python-docker
environment:
  OPTA_DISABLE_REPORTING: "true"
steps:
  - checkout-opta
  - install-python-dependencies
  - run:
      name: "Build opta binary"
      command: |
        source $(pipenv --venv)/bin/activate
        export PYTHONPATH=$(pwd)
        make build-binary
  - persist_to_workspace:
      root: ./
      paths:
        - dist