executor: ubuntu-machine
environment:
  OPTA_DISABLE_REPORTING: "true"
steps:
  - attach_workspace:
      at: ~/
  - run:
      name: "Check Opta Version"
      command: |
        $HOME/.opta/opta version