executor: python-docker
environment:
  OPTA_DISABLE_REPORTING: "true"
steps:
  - checkout-opta
  - when:
      condition: << pipeline.parameters.ci-use-diff-env >>
      steps:
        - remake-environment-configs
  - attach_workspace:
      at: ./
  - attach_workspace:
      at: ~/
  - install-opta-dependencies
  - gcp-cli/install
  - gcp-cli/initialize
  - run:
      name: "Setting up gcp envar"
      command: echo 'export GOOGLE_APPLICATION_CREDENTIALS="/home/circleci/gcloud-service-key.json"' >> $BASH_ENV
  - run:
      name: "Deploy test-service-helm"
      command: |
        $HOME/.opta/opta apply \
        --env gcpenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-gcp/service-helm.yml \
        --auto-approve
