executor: python-docker
environment:
  OPTA_DISABLE_REPORTING: "true"
steps:
  - checkout-opta
  - when:
      condition: << pipeline.parameters.ci-use-diff-env >>
      steps:
        - remake-environment-configs
  - attach_workspace:
      at: ./
  - attach_workspace:
      at: ~/
  - install-opta-dependencies
  - gcp-cli/install
  - gcp-cli/initialize
  - run:
      name: "Setting up gcp envar"
      command: echo 'export GOOGLE_APPLICATION_CREDENTIALS="/home/circleci/gcloud-service-key.json"' >> $BASH_ENV
  - run:
      name: "Configure Kubectl"
      command: |
        $HOME/.opta/opta configure-kubectl \
        --config ./.circleci/ci-tests/create-and-destroy-gcp/environment.yml
  - run:
      name: "Destroy K8s Manifest with Opta"
      command: |
        $HOME/.opta/opta destroy \
        --env gcpenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-gcp/k8s-manifest.yaml \
        --auto-approve || if [[ $? -eq 141 ]]; then true; else exit $?; fi