executor: ubuntu-machine
environment:
  OPTA_DISABLE_REPORTING: "true"
steps:
  - checkout-opta
  - install-python
  - when:
      condition: << pipeline.parameters.ci-use-diff-env >>
      steps:
        - remake-environment-configs
  - attach_workspace:
      at: ~/
  - attach_workspace:
      at: ./
  - install-opta-dependencies
  - gcp-cli/install
  - gcp-cli/initialize
  - run:
      name: "Setting up gcp envar"
      command: echo 'export GOOGLE_APPLICATION_CREDENTIALS="/home/circleci/gcloud-service-key.json"' >> $BASH_ENV
  - run:
      name: "Load test-service image"
      command: docker load -i test-service-image
  - run:
      name: "Set secret"
      command: |
        yes | $HOME/.opta/opta secret update \
        --env gcpenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-gcp/service-pg.yml \
        FAKE_SECRET foo || if [[ $? -eq 141 ]]; then true; else exit $?; fi
  - run:
      name: "Deploy test-service-pg"
      command: |
        yes | $HOME/.opta/opta deploy \
        --image app:latest \
        --env gcpenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-gcp/service-pg.yml \
        --tag $CIRCLE_SHA1 \
        --auto-approve || if [[ $? -eq 141 ]]; then true; else exit $?; fi
  - run:
      name: "Deploy test-service with Additional PG"
      command: |
        yes | $HOME/.opta/opta deploy \
        --image app:latest \
        --env gcpenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-gcp/service-additional-pg.yml \
        --tag $CIRCLE_SHA1 \
        --auto-approve || if [[ $? -eq 141 ]]; then true; else exit $?; fi
  - run:
      name: "Deploy test-service remove Additional PG"
      command: |
        yes | $HOME/.opta/opta deploy \
        --image app:latest \
        --env gcpenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-gcp/service-pg.yml \
        --tag $CIRCLE_SHA1 \
        --auto-approve || if [[ $? -eq 141 ]]; then true; else exit $?; fi
  - run:
      name: "View secret and check value"
      command: |
        secret_value=$($HOME/.opta/opta secret view \
        --env gcpenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-gcp/service-pg.yml \
        FAKE_SECRET | grep foo)
        echo "This was the found secret value: ${secret_value}"
        [[ "$secret_value" =~ .*"foo".* ]] || exit 1
  - run:
      name: "Destroy test-service-pg"
      command: |
        yes | $HOME/.opta/opta destroy \
        --env gcpenv-ci \
        --config ./.circleci/ci-tests/create-and-destroy-gcp/service-pg.yml \
        --auto-approve || if [[ $? -eq 141 ]]; then true; else exit $?; fi