executor: python-docker
steps:
  - checkout-opta
  - install-python-dependencies-development
  - run:
      name: "Lint"
      command: |
        source $(pipenv --venv)/bin/activate
        export PYTHONPATH=$(pwd)
        ./scripts/lint.py