# This opta environment is used by the test-ci job in the runxc repo.
name: awsenv-ci-sachin
org_name: runx
providers:
  aws:
    region: us-east-2
    account_id: 652824372180
modules:
  - type: base
  - type: dns
    domain: opta-ci.runx.dev
    delegated: false
  - type: k8s-cluster
    max_nodes: 6
    spot_instances: true
  - type: k8s-base
    admin_arns:
      - "arn:aws:iam::652824372180:user/github-actions"
