environments:
    - name: awsenv-ci
      path: "environment.yml"
      variables: {}
name: testservice-ci
modules:
  - type: k8s-service
    name: app
    public_uri: "test-service.{parent.domain}"
    port:
      http: 5000
    image: AUTO
    healthcheck_path: "/healthcheck"
    env_vars:
      - name: APPENV
        value: "{env}"
      - name: BUCKET_NAME
        value: "${{module.bucket.bucket_id}}"
    secrets:
      - FAKE_SECRET
    links:
      - pg
      - docdb
      - redis
      - bucket: ["write"]
  - name: pg
    type: postgres
    safety: false
  - name: docdb
    type: aws-documentdb
  - name: redis
    type: redis
    node_type: "cache.t3.micro"
  - name: bucket
    type: aws-s3
    bucket_name: "runx-testservice-ci-bucket-{env}"
  - name: redishelm
    type: helm-chart
    chart: redis
    chart_version: "15.3.2"
    repository: "https://charts.bitnami.com/bitnami"