halt: false
environment_module: false
inputs:
  - name: sku_name
    user_facing: true
    validator: str(required=False)
    description:  The name of the SKU, follows the tier + family + cores pattern for Azure postgres [instances](https://docs.microsoft.com/en-us/azure/postgresql/concepts-pricing-tiers).
    default: GP_Gen5_4
  - name: engine_version
    user_facing: true
    validator: str(required=False)
    description: The version of the database to use.
    default: "11"
outputs:
  - name: db_user
    export: true
    description: The database user
  - name: db_password
    export: false
    description: The database password
  - name: db_host
    export: true
    description: The database host
  - name: db_name
    export: true
    description: The database ip
output_providers: { }
output_data: { }