halt: false
environment_module: true
inputs:
  - name: private_key
    user_facing: false
    description: Private key for external ssl cert
    default: ""
  - name: certificate_body
    user_facing: false
    description: Cert body for external ssl cert
    default: ""
  - name: certificate_chain
    user_facing: false
    description: Cert body for external ssl cert
    default: ""
  - name: nginx_high_availability
    user_facing: true
    validator: bool(required=False)
    description: Deploy the nginx ingress in a high-availability configuration.
    default: false
  - name: linkerd_high_availability
    user_facing: true
    validator: bool(required=False)
    description: Deploy the linkerd service mesh in a high-availability configuration for its control plane.
    default: false
  - name: linkerd_enabled
    user_facing: true
    validator: bool(required=False)
    description: Enable the linkerd service mesh installation.
    default: true
  - name: nginx_config
    user_facing: true
    validator: any(required=False)
    description: Additional configuration for nginx ingress. [Available options](https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/configmap/#configuration-options)
    default: false
outputs:
  - name: load_balancer_raw_ip
    export: bool
    description: str
output_providers: { }
output_data: { }