halt: false
environment_module: false
inputs:
  - name: fifo
    user_facing: true
    validator: bool(required=False)
    description: FIFO queue or not.
    default: false
  - name: content_based_deduplication
    user_facing: true
    validator: bool(required=False)
    description: Duplicate content
    default: false
  - name: sqs_subscribers
    user_facing: true
    validator: list(str(), required=False)
    description: List of SQS ARNs to push from this topic.
    default: []
outputs:
  - name: topic_arn
    export: true
    description: Arn of the topic jsut created
  - name: kms_arn
    export: true
    description: Arn of the kms key created to encrypt this topi
output_providers: { }
output_data: { }