halt: true
environment_module: true
is_unique: true
inputs:
  - name: env_name
    user_facing: false
    description: Opta Environment name
    default: None
  - name: layer_name
    user_facing: false
    description: Opta Layer name
    default: None
  - name: module_name
    user_facing: false
    description: Opta Module name
    default: None
  - name: total_ipv4_cidr_block
    user_facing: true
    validator: any(required=False)
    description: This is the total cidr block for the VPC.
    default: "10.0.0.0/16"
  - name: private_ipv4_cidr_blocks
    user_facing: true
    validator: any(required=False)
    description: These are the cidr blocks to use for the private subnets, one for each AZ.
    default: ["10.0.128.0/21", "10.0.136.0/21", "10.0.144.0/21"]
  - name: public_ipv4_cidr_blocks
    user_facing: true
    validator: any(required=False)
    description: These are the cidr blocks to use for the public subnets, one for each AZ.
    default: ["10.0.0.0/21", "10.0.8.0/21", "10.0.16.0/21"]
outputs:
  - name: kms_account_key_arn
    export: true
    description: The [ARN](https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html) of the default [KMS](https://aws.amazon.com/kms/) key (this is what handles encryption for redis, documentdb, eks, etc…)
  - name: kms_account_key_id
    export: true
    description: The [ID](https://docs.aws.amazon.com/kms/latest/developerguide/find-cmk-id-arn.html) of the default KMS key (sometimes things need the ID, sometimes the ARN, so we’re giving both)
  - name: vpc_id
    export: true
    description: The ID of the [VPC](https://docs.aws.amazon.com/vpc/latest/userguide/what-is-amazon-vpc.html) we created for this environment
  - name: private_subnet_ids
    export: true
    description: The IDs of the private [subnets](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html) we setup for your environment
  - name: public_subnets_ids
    export: true
    description: The IDs of the public [subnets](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html) we setup for your environment
  - name: s3_log_bucket_name
    export: true
    description: The name of the default logging bucket provisioned by opta
  - name: "public_nat_ips"
    export: true
    description: Public static IP of nat gateway(s)
output_providers: {}
output_data:
  aws_caller_identity:
    provider: {}
  aws_region:
    provider: {}
