halt: false
environment_module: true
inputs:
  - name: mail_from_prefix
    user_facing: bool
    validator: str(required=False)
    description: Subdomain to use with root domain.
    default: mail
outputs: { }
output_providers: { }
output_data: { }