halt: false
environment_module: false
inputs:
  - name: extra_iam_policies
    user_facing: true
    validator: list(str(), required=False)
    description: The arns of additional IAM policies to be attached to this role.
    default: []
  - name: links
    user_facing: true
    validator: list(any(str(), map()), required=False)
    description: The list of links to add permissions for to this role.
    default: []
outputs:
  - name: user_arn
    export: true
    description: The arn of the user just created
output_providers: { }
output_data: { }