halt: false
environment_module: false
inputs:
  - name: instance_class
    user_facing: true
    validator: str(required=False)
    description: This is the RDS instance type used for the Aurora cluster [instances](https://aws.amazon.com/rds/instance-types/).
    default: db.t3.medium
  - name: engine_version
    user_facing: true
    validator: str(required=False)
    description: The version of the database to use.
    default: "11.9"
  - name: multi_az
    user_facing: true
    validator: bool(required=False)
    description: Enable read-write replication across different availability zones on the same reason (doubles the cost, but needed for compliance). Can be added and updated at a later date without need to recreate.
    default: false
outputs:
  - name: db_user
    export: true
    description: The database user
  - name: db_password
    export: false
    description: The database password
  - name: db_host
    export: true
    description: The database host
  - name: db_name
    export: true
    description: The database ip
output_providers: { }
output_data: { }