halt: false
environment_module: false
inputs:
  - name: engine_version
    user_facing: true
    validator: str(required=False)
    description: The version of mongodb to use
    default: "4.0.0"
  - name: instance_class
    user_facing: true
    validator: str(required=False)
    description: This is the RDS instance type used for the documentdb cluster [instances](https://aws.amazon.com/documentdb/pricing/).
    default: "db.r5.large"
outputs:
  - name: db_host
    export: true
    description: The host of the database.
  - name: db_user
    export: true
    description: The user of the database.
  - name: db_password
    export: false
    description: The password of the database.
output_providers: {}
output_data: {}