halt: false
environment_module: false
inputs:
  - name: env_name
    user_facing: false
    description: Opta Environment name
    default: None
  - name: layer_name
    user_facing: false
    description: Opta Layer name
    default: None
  - name: module_name
    user_facing: false
    description: Opta Module name
    default: None
  - name: allowed_k8s_services
    user_facing: true
    validator: list(include('allowed-k8s-services'), required=False)
    description: K8s service accounts that this role should have access to.
    default: []
  - name: links
    user_facing: true
    validator: list(any(str(), map()), required=False)
    description: A list of extra IAM role policies not captured by Opta which you wish to give to your service.
    default: []
  - name: read_buckets
    user_facing: false
    description: Buckets linked for reading
    default: []
  - name: write_buckets
    user_facing: false
    description: Buckets linked for writing
    default: []
extra_validators:
  allowed-k8s-services:
    service_account_name: str(required=True)
    namespace: str(required=True)
outputs:
  - name: service_account_id
    export: true
    description: The id of the GCP service account created
  - name: service_account_email
    export: true
    description: The email of the GCP service account created
output_providers: { }
output_data: { }