halt: false
environment_module: false
inputs:
  - name: instance_tier
    user_facing: true
    validator: str(required=False)
    description:  This is the RDS instance type used for the cloud sql instance [instances](https://cloud.google.com/sql/pricing).
    default: db-f1-micro
  - name: safety
    user_facing: true
    validator: bool(required=False)
    description:  Set to "true", if you want to disable the database deletion in Opta. You would have to manually set this "false" to enable DB deletion.
    default: false
  - name: engine_version
    user_facing: true
    validator: str(required=False)
    description: The version of the database to use.
    default: "5_7"
outputs:
  - name: db_name
    export: true
    description: The database user
  - name: db_password
    export: false
    description: The database password
  - name: db_host
    export: true
    description: The database host
  - name: db_name
    export: true
    description: The database ip
output_providers: { }
output_data: { }