{{- if eq (len .Values.persistentStorage) 0 }}
{{- if .Values.deployPods }}
{{- if ne "0" (toString .Values.autoscaling.maxReplicas) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "k8s-service.fullname" . }}
  labels:
    tags.datadoghq.com/service: {{ include "k8s-service.serviceName" . }}-{{ include "k8s-service.namespaceName" . }}
    tags.datadoghq.com/version: {{ .Values.version | quote }}
    {{- include "k8s-service.labels" . | nindent 4 }}
  namespace: {{ include "k8s-service.namespaceName" . }}
spec:
  selector:
    matchLabels:
      {{- include "k8s-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "k8s-service.selectorLabels" . | nindent 8 }}
        {{- include "k8s-service.optaLabels" . | nindent 8 }}
        tags.datadoghq.com/service: {{ include "k8s-service.serviceName" . }}-{{ include "k8s-service.namespaceName" . }}
        tags.datadoghq.com/version: {{ .Values.version | quote }}
        {{- range $k, $v := $.Values.podLabels }}
        {{ $k | quote }}: {{ $v | quote }}
        {{- end }}
      annotations:
        cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        # Outbound ports that should skip the proxy: datadog agent UDP (8126), postgres (5432), MySQL (3306)
        # with latest version of linkerd the DB ports would be marked as opaque, we should try removing them from this list
        # we will need to keep datadog since linkerd doesn't support UDP
        config.linkerd.io/skip-outbound-ports: "8126,5432,3306"
        linkerd-version: "2.10.2"
        ad.datadoghq.com/linkerd-proxy.check_names: '["linkerd"]'
        ad.datadoghq.com/linkerd-proxy.init_configs: '[{}]'
        ad.datadoghq.com/linkerd-proxy.instances: '[{"prometheus_url": "http://%%host%%:4191/metrics"}]'
        # See https://linkerd.io/2021/05/27/linkerd-vs-istio-benchmarks/
        config.linkerd.io/proxy-cpu-request: "0.05"
        config.linkerd.io/proxy-memory-limit: "100Mi"
        config.linkerd.io/proxy-memory-request: "20Mi"
        viz.linkerd.io/tap-enabled: "true"
        {{- range $k, $v := $.Values.podAnnotations }}
        {{ $k | quote }}: {{ $v | quote }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "k8s-service.serviceAccountName" . }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image }}"
          imagePullPolicy: Always
          volumeMounts:
            - name: config
              mountPath: "/config"
              readOnly: true
          {{- with .Values.ports }}
          ports:
            {{- range $portSpec := . }}
            - name: {{ $portSpec.name | quote }}
              protocol: TCP
              containerPort: {{ $portSpec.port }}
            {{- end }}
          {{- end }}
          env:
            - name: RDS_CA_PATH # This is the path to the public key for the docdb tls
              value: "/config/rds_ca.pem"
            {{ range .Values.envVars }}
            - name: {{ .name | quote }}
              value: {{ .value | quote }}
            {{ end }}
          envFrom:
          - secretRef:
              name: secret
              optional: true
          - secretRef:
              name: manual-secrets
              optional: true
          {{ if ne (len .Values.livenessProbeCommand ) 0 }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialLivenessDelay }}
            exec:
              command:
              {{- range $item := .Values.livenessProbeCommand }}
                 - {{ $item }}
              {{- end }}
          {{- end }}
          {{- if .Values.livenessProbePath }}
          livenessProbe:
            initialDelaySeconds: {{ .Values.initialLivenessDelay }}
            {{- if eq .Values.probePort.type "tcp" }}
            tcpSocket:
              port: {{ .Values.probePort.name | quote }}
            {{- else if eq .Values.probePort.type "http" }}
            httpGet:
              port: {{ .Values.probePort.name | quote }}
              path: {{ .Values.livenessProbePath }}
            {{- end }}
          {{- end }}
          {{- if .Values.readinessProbePath }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.initialReadinessDelay }}
            periodSeconds: 10
            {{- if eq .Values.probePort.type "tcp" }}
            tcpSocket:
              port: {{ .Values.probePort.name | quote }}
            {{- else if eq .Values.probePort.type "http" }}
            httpGet:
              port: {{ .Values.probePort.name | quote }}
              path: {{ .Values.readinessProbePath }}
            {{- end }}
          {{- end }}
          {{- if ne (len .Values.readinessProbeCommand ) 0 }}
          readinessProbe:
            initialDelaySeconds: {{ .Values.initialReadinessDelay }}
            exec:
              command:
                {{- range $item := .Values.readinessProbeCommand }}
                - {{ $item }}
                {{- end }}
          {{- end }}
          {{- if ne (len .Values.args ) 0 }}
          args:
          {{ range $arg := .Values.args }}
            - {{ $arg | quote }}
          {{ end }}
          {{- end }}
          {{- if ne (len .Values.commands ) 0 }}
          command:
          {{ range $arg := .Values.commands }}
            - {{ $arg | quote }}
          {{ end }}
          {{- end }}
          resources:
            limits:
              {{- toYaml .Values.containerResourceLimits | nindent 14 }}
            requests:
              {{- toYaml .Values.containerResourceRequests | nindent 14 }}
      volumes:
        - name: config
          configMap:
            name: {{ include "k8s-service.fullname" . }}
            items:
              - key: "rds_ca.pem"
                path: "rds_ca.pem"
      {{- if ne ( len .Values.tolerations ) 0 }}
      tolerations:
        {{ range $toleration :=  .Values.tolerations }}
        - key: {{ $toleration.key | quote }}
          value: {{ default "opta" $toleration.value | quote }}
          effect: {{ default "NoSchedule" $toleration.effect | quote }}
      {{ end }}
      {{- end }}
{{- end }}
{{- end }}
{{- end }}
