name: todoapi-ci
environments:
  - name: awsenv-ci
    path: "../create-and-destroy-aws/environment.yml"
  - name: awsenv-ci1
    path: "provider-aws.yml"
  - name: gcpenv-ci
    path: "../create-and-destroy-gcp/environment.yml"
  - name: gcpenv-ci1
    path: "provider-gcp.yml"
modules:
  - name: todoapi
    type: k8s-service
    port:
      http: 8000
    image: AUTO
    healthcheck_path: "ht/"
    links:
      - database:
        - db_user: POSTGRES_USER
          db_host: POSTGRES_HOST
          db_name: POSTGRES_DB
          db_password: POSTGRES_PASSWORD
    public_uri: "/djangoapi"
  - name: database
    type: postgres
