name: todomonitoring-ci
environments:
  - name: awsenv-ci
    path: "../create-and-destroy-aws/environment.yml"
  - name: awsenv-ci1
    path: "provider-aws.yml"
  - name: gcpenv-ci
    path: "../create-and-destroy-gcp/environment.yml"
  - name: gcpenv-ci1
    path: "provider-gcp.yml"
modules:
  - name: monitoring
    type: helm-chart
    chart: kube-prometheus-stack
    repository: 'https://prometheus-community.github.io/helm-charts'
    chart_version: '19.0.2'
    namespace: monitoring
    create_namespace: True
    values_file: "prometheus-grafana-monitoring-stack-values.yaml"
