apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "k8s-service.serviceAccountName" . }}
  labels:
    {{- include "k8s-service.labels" . | nindent 4 }}
  namespace: {{ include "k8s-service.namespaceName" . }}
