apiVersion: v1
kind: Secret
metadata:
  namespace: {{ include "k8s-service.namespaceName" . }}
  name: secret
type: Opaque
data:
  {{- $existing := (lookup "v1" "Secret" ( include "k8s-service.namespaceName" . ) "secret").data -}}
  {{- range $secret := .Values.linkSecrets }}
  {{ $secret.name }}: {{ if not ( eq $secret.value "" ) }} {{ $secret.value | b64enc }} {{ else }} {{ (default "Cg==" (get $existing $secret.name)) }} {{ end }}
  {{ end -}}
