halt: false
environment_module: true
inputs:
  - name: api_key
    user_facing: true
    validator: str(required=False)
    description: Datadog API key. If you don't provide this in the yaml, Opta will prompt you for it and store it in secrets.
    default: null
  - name: timeout
    user_facing: true
    validator: int(required=False)
    description: Time to wait for this module to stabilize.
    default: 600
  - name: values
    user_facing: true
    validator: any(required=False)
    description: Additional configuration for datadog. [Available options](https://github.com/DataDog/helm-charts/blob/master/charts/datadog/README.md#values)
    default: { }
outputs: { }
output_providers: { }
output_data: { }