environments:
  - name: env-tg
    path: "environment.yaml"
    variables:
      max_containers: 2
name: hello-opta
modules:
  - type: k8s-service
    name: hello
    port:
      http: 80
    image: ghcr.io/run-x/hello-opta/hello-opta:main
    healthcheck_path: "/"
    public_uri: "/hello"