# This workflow creates the environment & service layer from scratch using our
# deploy-action Github Action and then destroys them.
# This workflow should be run before each release of the github action,
# to ensure it still works.
name: Test Create and Destroy with Deploy Action

on: workflow_dispatch

jobs:
  create-and-destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Pin terraform version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 0.15.5
          terraform_wrapper: false
      # This test cannot be run concurrently because it is
      # creating and destroying real resources in the us-west-2 region.
      # Wait for any previous builds of this workflow to finish.
      - name: Limit concurrency to 1.
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_GITHUB_TOKEN }}
      - name: Checkout test-service repo
        uses: actions/checkout@v2
        with:
          repository: "run-x/test-service"
          path: "test-service"
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Checkout deploy-action repo
        uses: actions/checkout@v2
        with:
          repository: "run-x/deploy-action"
          path: "deploy-action"
          ssh-key: ${{ secrets.SSH_KEY }}
      - name: Setup ssh
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --dev
          source $(pipenv --venv)/bin/activate
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.DEPLOYER_AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.DEPLOYER_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build test-service image
        run: docker build -t app:latest -f test-service/Dockerfile test-service/
      - name: Deploy test-service with github action
        uses: run-x/deploy-action@master
        with:
          env: github-action
          image: app:latest
          tag: ${{ github.sha }}
          config: test-service/opta-ga-ci.yml
      - name: Destroy test service
        run: |
          source $(pipenv --venv)/bin/activate
          export PYTHONPATH=$(pwd)
          yes | python ./opta/cli.py destroy \
          --config test-service/opta-ga-ci.yml \
          --env github-action \
          --auto-approve
