name: GCP Additional Node Pool
on: workflow_dispatch

jobs:
  additional-gcp-nodepool:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Opta Repository
        uses: actions/checkout@v2

      - name: Pin terraform version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false

      - name: Limit concurrency to 1.
        uses: softprops/turnstyle@v1
        env:
          GITHUB_TOKEN: ${{ secrets.ALL_GITHUB_TOKEN }}

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.4.1
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Configure GCP credentials
        uses: google-github-actions/setup-gcloud@master
        with:
          service_account_key: ${{ secrets.CI_GKE_SA_KEY }}
          project_id: opta-ci-1
          export_default_credentials: true

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          pip install pipenv
          pipenv install --deploy --dev
          source $(pipenv --venv)/bin/activate
      - name: Build Release Binary
        run: |
          source $(pipenv --venv)/bin/activate
          export PYTHONPATH=$(pwd)
          make build-binary
      - name: Create Test Enrironment with no Additional Nodepool
        run: |
          OPTA_DISABLE_REPORTING=true ./dist/opta/opta apply \
          --config ./examples/ci-tests/gcp-nodepool/gcp-nodepool-state1.yml \
          --auto-approve \
          --refresh
      - name: Update Test Environment to have Additional Nodepool
        run: |
          OPTA_DISABLE_REPORTING=true ./dist/opta/opta apply \
          --config ./examples/ci-tests/gcp-nodepool/gcp-nodepool-state2.yml \
          --auto-approve \
          --refresh
      - name: Update Test Environment to remove Additional Nodepool
        run: |
          OPTA_DISABLE_REPORTING=true ./dist/opta/opta apply \
          --config ./examples/ci-tests/gcp-nodepool/gcp-nodepool-state1.yml \
          --auto-approve \
          --refresh
      - name: Destroy Test Enrironment
        run: |
          yes | OPTA_DISABLE_REPORTING=true ./dist/opta/opta destroy \
          --config ./examples/ci-tests/gcp-nodepool/gcp-nodepool-state1.yml \
          --auto-approve