name: Nightly Create and Destroy
on:
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  create-destroy-tests-aws:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: dev
      - name: Pin terraform version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false
      - name: Create and destroy test-service and opta environment
        run: ./scripts/dispatch_workflow.sh opta create-and-destroy-aws.yml dev
        env:
          github_token: ${{ secrets.ALL_GITHUB_TOKEN }}
      # - name: Slack alert if failed.
      #   if: ${{ failure() }}
      #   run: echo "TODO, send slack alert to notify failure"

  create-destroy-tests-gcp:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Pin terraform version
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.0.0
          terraform_wrapper: false
      - name: Create and destroy test-service and opta environment
        run: ./scripts/dispatch_workflow.sh opta create-and-destroy-gcp.yml dev
        env:
          github_token: ${{ secrets.ALL_GITHUB_TOKEN }}
      # - name: Slack alert if failed.
      #   if: ${{ failure() }}
      #   run: echo "TODO, send slack alert to notify failure"
