environments:
  - name: awsenv-ci
    path: "environment.yml"
    variables: {}
name: ci-redis
modules:
  - type: k8s-service
    port:
      http: 5000
    image: AUTO
    healthcheck_path: "/healthcheck"
    env_vars:
      - name: APPENV
        value: "{env}"
      - name: CLOUD_PROVIDER
        value: aws
      - name: TEST_S3
        value: "0"
      - name: TEST_POSTGRES
        value: "0"
      - name: TEST_DOCDB
        value: "0"
      - name: TEST_MYSQL
        value: "0"
    links:
      - redis
  - name: redis
    type: redis
    node_type: "cache.t3.micro"