environments:
  - name: awsenv-ci
    path: "environment.yml"
    variables: {}
name: ci-s3
modules:
  - type: k8s-service
    port:
      http: 5000
    image: AUTO
    healthcheck_path: "/healthcheck"
    env_vars:
      - name: APPENV
        value: "{env}"
      - name: CLOUD_PROVIDER
        value: aws
      - name: BUCKET_NAME
        value: "${{module.bucket.bucket_id}}"
      - name: TEST_POSTGRES
        value: "0"
      - name: TEST_REDIS
        value: "0"
      - name: TEST_DOCDB
        value: "0"
      - name: TEST_MYSQL
        value: "0"
    links:
      - bucket
  - name: bucket
    type: aws-s3
    bucket_name: "runx-ci-bucket-{env}"