environments:
    - name: awsenv-ci
      path: "environment.yml"
      variables: {}
name: ci-mysql
modules:
  - type: aws-mysql
    name: mysql
    safety: false
  - type: k8s-service
    port:
      http: 5000
    image: AUTO
    healthcheck_path: "/healthcheck"
    env_vars:
      - name: APPENV
        value: "{env}"
      - name: CLOUD_PROVIDER
        value: aws
      - name: TEST_S3
        value: "0"
      - name: TEST_REDIS
        value: "0"
      - name: TEST_POSTGRES
        value: "0"
      - name: TEST_DOCDB
        value: "0"
    links:
      - mysql:
        - db_user: MYUSER
          db_host: MYHOST
          db_name: MYDB
          db_password: MYPASS