environments:
  - name: awsenv-ci
    path: "environment.yml"
name: websocket-ci
modules:
  - name: app
    type: k8s-service
    image: ksdn117/web-socket-test
    port:
      tcp: 8010
    public_uri: "/websocket"