{{- if (and .Values.tls_crt .Values.tls_key) }}
apiVersion: v1
kind: Secret
metadata:
  name: secret-tls
  namespace: ingress-nginx
type: kubernetes.io/tls
data:
  tls.crt: |
    {{ .Values.tls_crt }}
  tls.key: |
    {{ .Values.tls_key }}
{{- end }}